services:
  backend: 
    image: py
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./Backend:/app
    restart: unless-stopped

  frontend:
    image: docconnect
    ports:
      - "3000:3000"
    volumes:
      - ./:/app                
    depends_on:
      - backend
    restart: unless-stopped
