services:
  backend:
    image: python
    container_name: backend_service
    ports:
      - "5000:5000"
    environment:
      - DOCKER_ENV=true
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    image: docconnect
    container_name: frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
